main: com.mythicacraft.plugins.mythsentials.Mythsentials
name: Mythsentials
version: 2.2
author: ebiggz
authors: [rockjolt375]
description: General purpose plugin for Mythica. 
depend: [JSONAPI]
commands:
    helpme:
        description: Sends an alert to admins/mods.
        usage: /<command> [reason]
    modhelp:
        description: Sends an alert to admins/mods.
        usage: /<command> [reason]
    adminhelp:
        description: Sends an alert to admins/mods.
        usage: /<command> [reason]
    mod:
        description: Sends an alert to admins/mods.
        usage: /<command> [reason]
    admin:
        description: Sends an alert to admins/mods.
        usage: /<command> [reason]
    mods:
        description: Tells you if mods are online.
        usage: /<command>
    admins:
        description: Tells you if mods are online.
        usage: /<command>
    restool:
        description: Gives you the res selection tool.
        usage: /<command>
    mythica:
        description: Shows Mythsentials help menu.
        usage: /<command> help
    spirebot:
        description: Shows Spirebot ?commands.
        usage: /<command> 
    dragon:
        description: Tells player if Dragon is alive or not.
        usage: /<command> 
    playerinfo:
        description: Mod command for viewing player info.
        useage: /<command> [playername]
    deathdrops:
        description: Mod command for viewing player death drops.
        useage: /<command> [playername]
    loginlocation:
        description: Mod command for setting player login location.
        useage: /<command> [playername]
    compass:
        description: Set your compass target.
        aliases: c
        useage: /<command>
    register:
        description: Allows users to enter email and password.
        usage: /<command>
    reg:
        description: Allows users to enter email and password.
        usage: /<command>
    confirm:
        description: Used for confirming registration information.
        usage: /<command>
    cancel:
        description: Used for cancelling registration.
        usage: /<command>
    pet:
        description: Used for pet commands.
        usage: /<command>
    mythicatest:
        description: Used for testing stuff.
        usage: /<command>
    resmax:
        description: Select a max res size.
        usage: /<command>
    colors:
        description: Shows all the color and format text codes.
        usage: /<command>
    formats:
        description: Shows all the color and format text codes.
        usage: /<command>
    colornames:
        description: Shows the color names with color.
        usage: /<command>
    colorname:
        description: Shows the color name with color.
        usage: /<command>
    prefix:
        description: Allows you to set a prefix to your name.
        usage: /<command> [prefix] - Leave blank to clear prefix
    suffix:
        description: Allows you to set a suffix to your name.
        usage: /<command> [suffix] - Leave blank to clear suffix
    color:
        description: Shortcut commands to change color of the prefix/name/suffix
        usage: /<command> [prefix/name/suffix] [colorname/clear]   
    affixer:
        description: Shows Affixer help menu.
        usage: /<command> ?/Help  - Shows help menu 
permissions:
    mythica.helpsend:
        default: false
    mythica.helpreceive:
        default: false
    mythica.restool:
        default: false
    mythica.registered:
        default: false
    mythica.admin:
        default: false
    mythica.mod:
        default: false
    mythica.colorsigntext:
        default: false
    mythica.invitools:
        default: false
    mythica.inviarmor:
        default: false
    mythica.test:
        default: op     
    mythica.*:
        default: op
        children:
            mythica.helpsend: true
            mythica.helpreceive: true
            mythica.restool: true
            mythica.registered: true
            mythica.colorsigntext: true
            mythica.admin: true
            mythica.mod: true
            mythica.invtools: true
            mythica.invarmor: true
            mythica.test: true
    affixer.colors:
        default: false
    affixer.colornames:
        default: false
    affixer.prefix:
        default: false
    affixer.suffix:
        default: false
    affixer.*:
        default: op
        children:
            affixer.colornames: true
            affixer.colors: true
            affixer.prefix: true
            affixer.suffix: true