main: com.mythicacraft.plugins.mythsentials.Mythsentials
name: Mythsentials
version: 2.2
author: ebiggz
authors: [rockjolt375]
description: General purpose plugin for Mythica. 
depend: [JSONAPI]
commands:
    helpme:
        description: Sends an alert to admins/mods.
        usage: /<command> [reason]
    modhelp:
        description: Sends an alert to admins/mods.
        usage: /<command> [reason]
    adminhelp:
        description: Sends an alert to admins/mods.
        usage: /<command> [reason]
    mod:
        description: Sends an alert to admins/mods.
        usage: /<command> [reason]
    admin:
        description: Sends an alert to admins/mods.
        usage: /<command> [reason]
    mods:
        description: Tells you if mods are online.
        usage: /<command>
    admins:
        description: Tells you if mods are online.
        usage: /<command>
    restool:
        description: Gives you the res selection tool.
        usage: /<command>
    mythica:
        description: Shows Mythsentials help menu.
        usage: /<command> help
    dragon:
        description: Tells player if Dragon is alive or not.
        usage: /<command> 
    playerinfo:
        description: Mod command for viewing player info.
        useage: /<command> [playername]
    deathdrops:
        description: Mod command for viewing player death drops.
        useage: /<command> [playername]
    loginlocation:
        description: Mod command for setting player login location.
        useage: /<command> [playername]
    compass:
        description: Set your compass target.
        aliases: c
        useage: /<command>
    register:
        description: Allows users to enter email and password.
        usage: /<command>
    reg:
        description: Allows users to enter email and password.
        usage: /<command>
    confirm:
        description: Used for confirming registration information.
        usage: /<command>
    cancel:
        description: Used for cancelling registration.
        usage: /<command>
    pet:
        description: Used for pet commands.
        usage: /<command>
    mythicatest:
        description: Used for testing stuff.
        usage: /<command>     
permissions:
    mythica.helpsend:
        default: false
    mythica.helpreceive:
        default: false
    mythica.restool:
        default: false
    mythica.registered:
        default: false
    mythica.admin:
        default: false
    mythica.mod:
        default: false
    mythica.colorsigntext:
        default: false
    mythica.invitools:
        default: false
    mythica.inviarmor:
        default: false
    mythica.test:
        default: op     
    mythica.*:
        default: op
        children:
            mythica.helpsend: true
            mythica.helpreceive: true
            mythica.restool: true
            mythica.registered: true
            mythica.colorsigntext: true
            mythica.admin: true
            mythica.mod: true
            mythica.invtools: true
            mythica.invarmor: true
            mythica.test: true